# Generated by Django 6.0.5 on 2026-05-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMSysApp', '0003_order_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
